{{- with .Values.objectstorage }}
{{- if eq (.enabled | toString) "true" }}
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .bucket.name }}
  namespace: {{ .bucket.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "2" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  generateBucketName: {{ .bucket.name }}
  storageClassName: {{ .bucket.storageclass }}
  additionalConfig:
    bucketclass: {{ .bucket.bucketclass }}
{{- end }}
{{- end }}
