apiVersion: v2
name: setup-gateway-api
description: OpenShift Gateway API - GatewayClass and shared Gateway in openshift-ingress.
home: https://github.com/mcapala/openshift-clusterconfig/tree/main/clusters/management-cluster/setup-gateway-api
version: 1.0.0
