{{- with .Values.gateway }}
{{- if eq (.enabled | toString) "true" }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "1" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  gatewayClassName: {{ $.Values.gatewayclass.name }}
  listeners:
    {{- toYaml .listeners | nindent 4 }}
{{- end }}
{{- end }}
