---
generic-cluster-config:
  console:
    console_banners:
      topbanner:
        enabled: true
        text: 'Management Cluster'
        location: BannerTop
        color: "#FFFFFF"
        backgroundcolor: '#FF0000'
