---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgA/iinCjbjIVDw68KEph6jnVI5RVJ8A9EkcaQy/MH8SBqVhdWk9SXLcWZib1LxGn3bmiGwfL7y/Q2bhVsUaonF6WBBuZqjubsI7tdHoc4bHxs/TJfYi7nXHe9hT29bdQKABVJb1EpZbg5fV5cuiyTfP2ZYnTslFeY3mGYYJXG1O87alOnZs5KrX5ths5aYcOpJ7CdtfrkRyvRgm1JVh4Idz6E2VNTEotHt73o6z9nYYU8emjrfLiAg4IlwgX+PsX3Ku7Nk/sD1eSUAxA6W43JPVy87X6Hx5j1JTByFy8v2bZTXlPS440pnKyQd10xfaSazlT2U6duSfDJGgn9U20fPGSMaurnpAFq2GjZNIqKOn03DOqn8exaUUew9t/FAcYeD0sUwjuauxwwgmS98xKWz2k0maxRGJCpettJBdaxhbLiyVLDA2pH+RKJh7ljHAjSM49yQytxK2VWUkbSdYSLPGRtTLnry0X65eBg+NUTPrnC1nbO+NXgMHg0h+86w57EURH92j7ZnwMYac9qJfZ4eHflk2RJjl6GvhZBgXp0C/x397NyP4uBnE6L/3fXVaJs1fE+wnqJ86ktH+6ZnQ+ueEpFRhuvDD6cX6xbUMqNbir2YB3ipafxNZ6ZMXPA+m2wAoV0mNJMhDH0fLjXjlzuBATMxFconOkwGeMnCmzNoaKzLxOM0U3lSTDAtGluj+LyppHsEmLwPJSPnegi/qbwJh2pE7UTIuLBe28+nyhgtiwQC4gByYfiWF
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
