---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBKWnTKFkXoF4fiZaoFoXAarMXU5Bd7iZnF7zCwwp1YhmxOXli7SWt1JUIuajDrk3mPnxO2x+3TTysNLlV3+QOCPtV6ueCm41aEyS+vY95d1q6Us1gl6ZTdVeuBx87GE8gV6e0OkuUGgY/Qw6T8dnqB1SqG8TNbO3TFfGa3Ox13x2vPbqzf6XTYlxzvSTbmBWWiAQUABmHnBYAF77vNR+60oWI7/IAxTU0J1gvh6dU33SRqciRvgV+H0cGE7uXu0A+QM+evzgei5QnqKGZgcHzaBTv88IrZOT/fEo6prRfe7l1M5Y4F19DUMFYeBJ9P4RYdKYL1M2Q5ffF2VBAu2/RSiXdagG7ZwjSfZbY3GKNvFP/nAQMFuGUqF1YTtAnrVUFUYZIWA3vJmJnsm892uez56eSngKXRBxVjuliqLyiRhmM3s7zkIg23LzcXdvcopSwA3bz6g6GTQCdY/Nl7OAH29cJKY68KzYtoRNuudJO7GIyX5I9lOywhYJGIqZf3xi5ObbIxa+rkauO72Fgx3LBWraJrfR64bSqUjiBjk8OdHLl9lCI0ALw8o+S5BDhv9Pyo5Oq0h7f8sikLJSXNltgDfMEKMP6ROlb28h3Cs1cYenONTpE6VFoKoJGV7GRW0huJjiLz+5R2i8WanrFLPcfCvx2ieByPOgIeHED1zORtFzqncT1NV3L47iW5HoTlL+7OxPnDz5ukGbMKecbvfOixeO9/umvjmUDSlIYJpty0m4eM4ZsQRs29
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
