---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: sealed-secrets-web
spec:
  encryptedData:
    api-key: AgCmI9RENgKupln71NiQOjdDgiN9s5VG9qlIszcWGIT3tmNrwjTw3Zjmx72z+mGLYq8hbwaYITflXYZAan7QOshPgW8+lyVLJqRjEuKHBBu3X0PYvLf/xpZ4OicIyV+vvOBqKTzJf/FhxnJFrJzL8I75hSYT8Nwee3ODh1r5vpm0DHb/wcW/BBknlKguBujZgaAG6MhNPngIPgY7IUtBYJLzg33cmy5mhPLqA2P7XkuqFrbVR+gBNexBOlcvJf7d8+0Eevsk95DNf2uEt3DpSYPnkyF5pac1DCC5ymYrmYONwserrO5bk3qo/an98wpUA/oIlVW+oAIgeAiPfZOZsI0ZrB4vXrpoMGLGVGNQRRdcPMqLvxHcJgELVdQQhu2glYyOiBe0iWIDLRo3lFwfMCahngkTp+Mpueqs2W3KsQE44BiMSZOcDGoh8gjydSdIMyF3LMLPSFsypmtyxX5Y/G8m7fNRR+up91k3FIeQiTWMuXTgYjbHntUVI4w7Mr+OPpDus15uQUcQTV7Rbs0RPtHfFTxLOKbyytgsOh+1GLmTNrGWoASVEvrAGZBLuWYZGhpZ573H50KtgtJep4BxW7GVI0NGnCJeCaPtrEEVUE1NX36lyjpi8rR6GHnfJwvTjzWUroYiEBL66Lqtbx47c6IQhu/gYylrGOm3iSa8oMW6IpUPzZ+OU0zj4Ho0cdBZljeVGE3gMtR5Zk9iLIFY/w4OzBVmuTVqOpPFF3bxvyfpfaCFjEnaFlC9
  template:
    metadata:
      name: cloudflare-api-key-secret
      namespace: sealed-secrets-web
    type: Opaque
