---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.namespace.syncwave | default "0" | quote }}
    openshift.io/description: {{ .Values.namespace.descr | quote }}
  labels:
    istio-discovery: enabled
    istio-injection: enabled
